/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.francopaiz.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.francopaiz.controlador.ControladorProveedores;
import org.francopaiz.controlador.ControladorServicios;

import org.francopaiz.controlador.ControladorTipoCuenta;
import org.francopaiz.modelo.TipoCuentas;
import org.francopaiz.modelo.TipoMonedas;
import org.francopaiz.controlador.ControladorTipoMonedas;
import org.francopaiz.modelo.Banco;
import org.francopaiz.controlador.ControladorBanco;
import org.francopaiz.modelo.Proveedores;
import org.francopaiz.modelo.Servicios;

/**
 * This is the Window for the admin mood.
 *
 * @author fpaiz
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnTipoCuentas = new javax.swing.JButton();
        btnTipoMoneda = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnDatosBanco = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTipoCuentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTipoCuenta = new javax.swing.JTextField();
        btnAgregarTipoCuenta = new javax.swing.JButton();
        btnEliminarTipoCuenta = new javax.swing.JButton();
        btnActualizarTipoCuenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdTipoCuenta = new javax.swing.JTextField();
        txtIdEliminarTipoCuenta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarTipoMoneda = new javax.swing.JButton();
        btnActualizarTipoMoneda = new javax.swing.JButton();
        btnEliminarMoneda = new javax.swing.JButton();
        txtIdTipoMoneda = new javax.swing.JTextField();
        txtTipoMoneda = new javax.swing.JTextField();
        txtIdMonedaEliminar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTipoMoneda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        btnAgregarProveedor = new javax.swing.JButton();
        btnActualizarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        txtIdEliminarProveedor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProveedores = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableServicios = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdServicio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        btnAgregarServicio = new javax.swing.JButton();
        btnActualizarServicio = new javax.swing.JButton();
        btnEliminarServicio = new javax.swing.JButton();
        txtIdEliminarServicio = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdBanco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreBanco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTelefonoBanco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDireccionBanco = new javax.swing.JTextField();
        txtPaginaBanco = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtGmailBanco = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableBanco = new javax.swing.JTable();
        btnAgregarBanco = new javax.swing.JButton();
        btnEliminarBanco = new javax.swing.JButton();
        txtIdEliminarBanco = new javax.swing.JTextField();
        btnActualizarBanco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTipoCuentas.setBackground(new java.awt.Color(255, 255, 153));
        btnTipoCuentas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTipoCuentas.setText("Tipos de Cuentas");
        btnTipoCuentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTipoCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCuentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTipoCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 38));

        btnTipoMoneda.setBackground(new java.awt.Color(255, 255, 153));
        btnTipoMoneda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTipoMoneda.setText("Tipo Moneda");
        btnTipoMoneda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoMonedaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 32));

        btnProveedores.setBackground(new java.awt.Color(255, 255, 153));
        btnProveedores.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 38));

        btnServicios.setBackground(new java.awt.Color(255, 255, 153));
        btnServicios.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 41));

        btnDatosBanco.setBackground(new java.awt.Color(255, 255, 153));
        btnDatosBanco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDatosBanco.setText("Datos del Banco");
        btnDatosBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDatosBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosBancoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDatosBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 49));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/francopaiz/recursos/Logo_G&T (2).png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 49));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("TIPOS DE CUENTAS");

        tableTipoCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Tipo Cuenta", "Cuenta"
            }
        ));
        jScrollPane1.setViewportView(tableTipoCuentas);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("INSERTAR TIPO DE CUENTA");

        btnAgregarTipoCuenta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAgregarTipoCuenta.setText("AGREGAR");
        btnAgregarTipoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoCuentaActionPerformed(evt);
            }
        });

        btnEliminarTipoCuenta.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarTipoCuenta.setText("ELIMINAR");
        btnEliminarTipoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoCuentaActionPerformed(evt);
            }
        });

        btnActualizarTipoCuenta.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarTipoCuenta.setText("ACTUALIZAR");
        btnActualizarTipoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTipoCuentaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("ID DE LA CUENTA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnEliminarTipoCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdEliminarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtIdTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizarTipoCuenta)
                            .addComponent(btnAgregarTipoCuenta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(txtIdEliminarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnActualizarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminarTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuentas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("TIPOS DE MONEDAS");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("ID DE LA MONEDA:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("INSERTAR TIPO DE MONEDA");

        btnAgregarTipoMoneda.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarTipoMoneda.setText("AGREGAR");
        btnAgregarTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoMonedaActionPerformed(evt);
            }
        });

        btnActualizarTipoMoneda.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarTipoMoneda.setText("ACTUALIZAR");
        btnActualizarTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTipoMonedaActionPerformed(evt);
            }
        });

        btnEliminarMoneda.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarMoneda.setText("ELIMINAR:");
        btnEliminarMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMonedaActionPerformed(evt);
            }
        });

        tableTipoMoneda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Tipo Moneda", "Moneda"
            }
        ));
        jScrollPane2.setViewportView(tableTipoMoneda);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(txtTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtIdTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarTipoMoneda)
                            .addComponent(btnAgregarTipoMoneda))))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnEliminarMoneda)
                .addGap(47, 47, 47)
                .addComponent(txtIdMonedaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnAgregarTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnActualizarTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdMonedaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Moneda", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("PROVEEDORES");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("ID DEL PROVEEDOR");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("INSERTAR EL PROVEEDOR");

        btnAgregarProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarProveedor.setText("AGREGAR");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        btnActualizarProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarProveedor.setText("ACTUALIZAR");
        btnActualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProveedorActionPerformed(evt);
            }
        });

        btnEliminarProveedor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarProveedor.setText("ELIMINAR:");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });

        tableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Proveedor", "Proveedor"
            }
        ));
        jScrollPane3.setViewportView(tableProveedores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(209, 402, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarProveedor)
                            .addComponent(btnAgregarProveedor)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnEliminarProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnActualizarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtIdEliminarProveedor))
                .addGap(83, 83, 83))
        );

        jTabbedPane1.addTab("Proveedores", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Servicio", "Servicio"
            }
        ));
        jScrollPane4.setViewportView(tableServicios);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("SERVICIOS");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("ID DEL SERVICIO:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("INSERTAR EL SERVICIO");

        btnAgregarServicio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarServicio.setText("AGREGAR");
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        btnActualizarServicio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarServicio.setText("ACTUALIZAR");
        btnActualizarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarServicioActionPerformed(evt);
            }
        });

        btnEliminarServicio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarServicio.setText("ELIMINAR:");
        btnEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(txtServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarServicio)
                            .addComponent(btnAgregarServicio)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnEliminarServicio)
                        .addGap(38, 38, 38)
                        .addComponent(txtIdEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnActualizarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Servicios", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/francopaiz/recursos/banco guate.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("BANCO");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("ID DEL BANCO:");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("NOMBRE:");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("TELEFONO :");

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setText("DIRECCION:");

        txtDireccionBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionBancoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setText("PAGINA:");

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setText("GMAIL:");

        tableBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Banco", "Nombre", "Telefono", "Direccion", "Pagina", "Gmail"
            }
        ));
        jScrollPane5.setViewportView(tableBanco);

        btnAgregarBanco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAgregarBanco.setText("AGREGAR");
        btnAgregarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBancoActionPerformed(evt);
            }
        });

        btnEliminarBanco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminarBanco.setText("ELIMINAR");
        btnEliminarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBancoActionPerformed(evt);
            }
        });

        btnActualizarBanco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnActualizarBanco.setText("ACTUALIZAR");
        btnActualizarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefonoBanco))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIdBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDireccionBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPaginaBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(txtGmailBanco))
                                .addGap(43, 43, 43)
                                .addComponent(btnAgregarBanco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizarBanco)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnEliminarBanco)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdEliminarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtNombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtTelefonoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtDireccionBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtPaginaBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGmailBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEliminarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Banco", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 18, 750, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // VARIABLES
    ControladorTipoCuenta controladorTipoCuenta = new ControladorTipoCuenta();
    DefaultTableModel modeloTipoCuenta = new DefaultTableModel();

    ControladorTipoMonedas controladorM = new ControladorTipoMonedas();
    DefaultTableModel modeloMoneda = new DefaultTableModel();

    ControladorServicios controladorS = new ControladorServicios();
    DefaultTableModel modeloServicio = new DefaultTableModel();

    ControladorProveedores controladorP = new ControladorProveedores();
    DefaultTableModel modeloProveedores = new DefaultTableModel();

    ControladorBanco controladorB = new ControladorBanco();
    DefaultTableModel modeloBanco = new DefaultTableModel();

    DefaultTableModel limpiar;
    DefaultTableModel limpiartipoCuentas;

    // LIMPIAR
    /**
     * This method has the function to clean the table of the coin.
     */
    public void limpiarTableMonedas() {
        modeloMoneda = (DefaultTableModel) tableTipoMoneda.getModel();
        int fila = tableTipoMoneda.getRowCount();
        for (int i = 0; i < fila; i++) {
            modeloMoneda.removeRow(0);
        }
    }

    /**
     * This method has the function to clean the table of the account.
     */
    public void limpiarTableCuentas() {
        modeloTipoCuenta = (DefaultTableModel) tableTipoCuentas.getModel();
        int fila = tableTipoCuentas.getRowCount();
        for (int i = 0; i < fila; i++) {
            modeloTipoCuenta.removeRow(0);
        }
    }

    /**
     * * This method has the function to clean the table of the bank.
     */
    public void limpiarTableBanco() {
        limpiar = (DefaultTableModel) tableBanco.getModel();
        int fila = tableBanco.getRowCount();
        for (int i = 0; i < fila; i++) {
            limpiar.removeRow(0);
        }
    }

    /**
     * * This method has the function to clean the table of the types of
     * accounts.
     */
    public void limpiarTableTipoCuentas() {
        limpiar = (DefaultTableModel) tableTipoCuentas.getModel();
        int fila = tableTipoCuentas.getRowCount();
        for (int i = 0; i < fila; i++) {
            limpiar.removeRow(0);
        }
    }

    /**
     * This method has the function to clean the table of the provider.
     */
    public void limpiarTableProveedores() {
        limpiar = (DefaultTableModel) tableProveedores.getModel();
        int fila = tableProveedores.getRowCount();
        for (int i = 0; i < fila; i++) {
            limpiar.removeRow(0);
        }
    }

    /**
     * This method has the function to clean the table of the service.
     */
    public void limpiarTableServicios() {
        limpiar = (DefaultTableModel) tableServicios.getModel();
        int fila = tableServicios.getRowCount();
        for (int i = 0; i < fila; i++) {
            limpiar.removeRow(0);
        }
    }

    /**
     * This method is to list the types of accounts in the table.
     */
    public void listarTipoCuentas() {
        ArrayList<TipoCuentas> ListarTP = controladorTipoCuenta.listarTipoCuenta();
        modeloTipoCuenta = (DefaultTableModel) tableTipoCuentas.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < ListarTP.size(); i++) {
            ob[0] = ListarTP.get(i).getId_tipo_cuenta();
            ob[1] = ListarTP.get(i).getTipo_cuenta();
            modeloTipoCuenta.addRow(ob);
        }

        tableTipoCuentas.setModel(modeloTipoCuenta);
    }

    /**
     * * This method is to list the types of coins in the table.
     */
    public void listarTipoMonedas() {
        ArrayList<TipoMonedas> ListarTM = controladorM.listarTipoMoneda();
        modeloMoneda = (DefaultTableModel) tableTipoMoneda.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < ListarTM.size(); i++) {
            ob[0] = ListarTM.get(i).getId_tipo_moneda();
            ob[1] = ListarTM.get(i).getMoneda();
            modeloMoneda.addRow(ob);
        }

        tableTipoMoneda.setModel(modeloMoneda);
    }

    /**
     * * This method is to list the types of services in the table.
     */
    public void listarServicios() {
        ArrayList<Servicios> ListarS = controladorS.listarServicios();
        modeloServicio = (DefaultTableModel) tableServicios.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < ListarS.size(); i++) {
            ob[0] = ListarS.get(i).getIdServicio();
            ob[1] = ListarS.get(i).getServicio();
            modeloServicio.addRow(ob);
        }

        tableServicios.setModel(modeloServicio);
    }

    /**
     * This method is to list the types of providers in the table.
     */
    public void listarProveedores() {
        ArrayList<Proveedores> ListarP = controladorP.listarProveedores();
        modeloProveedores = (DefaultTableModel) tableProveedores.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < ListarP.size(); i++) {
            ob[0] = ListarP.get(i).getIdProveedor();
            ob[1] = ListarP.get(i).getProveedor();
            modeloProveedores.addRow(ob);
        }

        tableProveedores.setModel(modeloProveedores);
    }

    /**
     * This method is to list the banks in the table.
     */
    public void listarBanco() {
        ArrayList<Banco> ListarB = controladorB.listarBanco();
        modeloBanco = (DefaultTableModel) tableBanco.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarB.size(); i++) {
            ob[0] = ListarB.get(i).getId_banco();
            ob[1] = ListarB.get(i).getNombreBanco();
            ob[2] = ListarB.get(i).getTelefonoBanco();
            ob[3] = ListarB.get(i).getDireccionBanco();
            ob[4] = ListarB.get(i).getPaginaBanco();
            ob[5] = ListarB.get(i).getGmailBanco();
            modeloBanco.addRow(ob);
        }

        tableBanco.setModel(modeloBanco);
    }
    private void btnTipoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCuentasActionPerformed
        // TODO add your handling code here:
        limpiarTableCuentas();
        jTabbedPane1.setSelectedIndex(0);
        listarTipoCuentas();
    }//GEN-LAST:event_btnTipoCuentasActionPerformed

    private void btnTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoMonedaActionPerformed
        // TODO add your handling code here:
        limpiarTableMonedas();
        jTabbedPane1.setSelectedIndex(1);
        listarTipoMonedas();
    }//GEN-LAST:event_btnTipoMonedaActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        limpiarTableServicios();
        jTabbedPane1.setSelectedIndex(3);
        listarServicios();
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnDatosBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosBancoActionPerformed
        // TODO add your handling code here:
        limpiarTableBanco();
        jTabbedPane1.setSelectedIndex(4);
        listarBanco();
    }//GEN-LAST:event_btnDatosBancoActionPerformed

    private void btnAgregarTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoCuentaActionPerformed
        // TODO add your handling code here:
        limpiarTableCuentas();
        TipoCuentas tipo = new TipoCuentas();
        tipo.setId_tipo_cuenta(Integer.parseInt(txtIdTipoCuenta.getText()));
        tipo.setTipo_cuenta(txtTipoCuenta.getText());
        ControladorTipoCuenta controlador = new ControladorTipoCuenta();
        controlador.agregarTipoCuenta(tipo);
        listarTipoCuentas();
        txtIdTipoCuenta.setText("");
        txtTipoCuenta.setText("");

    }//GEN-LAST:event_btnAgregarTipoCuentaActionPerformed

    private void btnEliminarTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoCuentaActionPerformed
        // TODO add your handling code here:
        limpiarTableCuentas();
        TipoCuentas tipo = new TipoCuentas();
        if (!"".equals(txtIdEliminarTipoCuenta.getText())) {
            tipo.setId_tipo_cuenta(Integer.parseInt(txtIdEliminarTipoCuenta.getText()));
            ControladorTipoCuenta controlador = new ControladorTipoCuenta();
            controlador.eliminarTipoCuenta(tipo);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para eliminarlo");
        }
        listarTipoCuentas();
        txtIdTipoCuenta.setText("");
        txtTipoCuenta.setText("");

    }//GEN-LAST:event_btnEliminarTipoCuentaActionPerformed

    private void btnActualizarTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTipoCuentaActionPerformed
        // TODO add your handling code here:
        limpiarTableCuentas();
        TipoCuentas tipo = new TipoCuentas();
        if (!"".equals(txtIdTipoCuenta.getText())) {
            tipo.setId_tipo_cuenta(Integer.parseInt(txtIdTipoCuenta.getText()));
            tipo.setTipo_cuenta(txtTipoCuenta.getText());
            ControladorTipoCuenta controlador = new ControladorTipoCuenta();
            controlador.actualizarTipoCuenta(tipo);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para actualizarlo");
        }
        listarTipoCuentas();
        txtIdTipoCuenta.setText("");
        txtTipoCuenta.setText("");

    }//GEN-LAST:event_btnActualizarTipoCuentaActionPerformed

    private void btnAgregarTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoMonedaActionPerformed
        // TODO add your handling code here:
        limpiarTableMonedas();
        TipoMonedas tipo = new TipoMonedas();
        tipo.setId_tipo_moneda(Integer.parseInt(txtIdTipoMoneda.getText()));
        tipo.setMoneda(txtTipoMoneda.getText());
        ControladorTipoMonedas controlador = new ControladorTipoMonedas();
        controlador.agregarTipoMoneda(tipo);

        listarTipoMonedas();
        txtIdTipoMoneda.setText("");
        txtIdTipoMoneda.setText("");
    }//GEN-LAST:event_btnAgregarTipoMonedaActionPerformed

    private void btnEliminarMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMonedaActionPerformed
        // TODO add your handling code here:
        limpiarTableMonedas();
        TipoMonedas tipo = new TipoMonedas();
        if (!"".equals(txtIdMonedaEliminar.getText())) {
            tipo.setId_tipo_moneda(Integer.parseInt(txtIdMonedaEliminar.getText()));
            ControladorTipoMonedas controlador = new ControladorTipoMonedas();
            controlador.eliminarTipoMoneda(tipo);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para eliminarlo");
        }
        listarTipoMonedas();
        txtIdTipoMoneda.setText("");
        txtIdTipoMoneda.setText("");
    }//GEN-LAST:event_btnEliminarMonedaActionPerformed

    private void btnActualizarTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTipoMonedaActionPerformed
        // TODO add your handling code here:
        limpiarTableMonedas();
        TipoMonedas tipo = new TipoMonedas();
        if (!"".equals(txtIdTipoMoneda.getText())) {
            tipo.setId_tipo_moneda(Integer.parseInt(txtIdTipoMoneda.getText()));
            tipo.setMoneda(txtTipoMoneda.getText());
            ControladorTipoMonedas controlador = new ControladorTipoMonedas();
            controlador.actualizarTipoMoneda(tipo);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para actualizarlo");
        }
        listarTipoMonedas();
        txtIdTipoMoneda.setText("");
        txtIdTipoMoneda.setText("");

    }//GEN-LAST:event_btnActualizarTipoMonedaActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:

        Proveedores prov = new Proveedores();
        limpiarTableProveedores();
        prov.setIdProveedor(Integer.parseInt(txtIdProveedor.getText()));
        prov.setProveedor(txtProveedor.getText());
        ControladorProveedores controlador = new ControladorProveedores();
        controlador.agregarProveedor(prov);
        listarProveedores();
        txtIdProveedor.setText("");
        txtProveedor.setText("");
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnActualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProveedorActionPerformed
        // TODO add your handling code here:
        limpiarTableProveedores();
        Proveedores prov = new Proveedores();
        if (!"".equals(txtIdProveedor.getText())) {
            prov.setIdProveedor(Integer.parseInt(txtIdProveedor.getText()));
            prov.setProveedor(txtProveedor.getText());
            ControladorProveedores controlador = new ControladorProveedores();
            controlador.actualizarProveedor(prov);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para actualizarlo");
        }
        listarProveedores();
        txtIdProveedor.setText("");
        txtProveedor.setText("");

    }//GEN-LAST:event_btnActualizarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        limpiarTableProveedores();
        Proveedores prov = new Proveedores();
        if (!"".equals(txtIdEliminarProveedor.getText())) {
            prov.setIdProveedor(Integer.parseInt(txtIdEliminarProveedor.getText()));
            ControladorProveedores controlador = new ControladorProveedores();
            controlador.eliminarProveedor(prov);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para eliminarlo");
        }
        listarProveedores();
        txtIdProveedor.setText("");
        txtProveedor.setText("");

    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        // TODO add your handling code here:

        Servicios servicio = new Servicios();
        limpiarTableServicios();
        servicio.setIdServicio(Integer.parseInt(txtIdServicio.getText()));
        servicio.setServicio(txtServicio.getText());
        ControladorServicios controlador = new ControladorServicios();
        controlador.agregarServicio(servicio);

        listarServicios();
        txtIdServicio.setText("");
        txtServicio.setText("");
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnActualizarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarServicioActionPerformed
        // TODO add your handling code here:
        limpiarTableServicios();
        Servicios servicio = new Servicios();
        if (!"".equals(txtIdServicio.getText())) {
            servicio.setIdServicio(Integer.parseInt(txtIdServicio.getText()));
            servicio.setServicio(txtServicio.getText());
            ControladorServicios controlador = new ControladorServicios();
            controlador.actualizarServicio(servicio);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para actualizarlo");
        }
        txtIdServicio.setText("");
        txtServicio.setText("");
        listarServicios();
    }//GEN-LAST:event_btnActualizarServicioActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
        // TODO add your handling code here:
        limpiarTableServicios();
        Servicios servicio = new Servicios();
        if (!"".equals(txtIdEliminarServicio.getText())) {
            servicio.setIdServicio(Integer.parseInt(txtIdEliminarServicio.getText()));
            ControladorServicios controlador = new ControladorServicios();
            controlador.eliminarServicio(servicio);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para eliminarlo");
        }
        txtIdServicio.setText("");
        txtServicio.setText("");
        listarServicios();
    }//GEN-LAST:event_btnEliminarServicioActionPerformed

    private void txtDireccionBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionBancoActionPerformed

    private void btnAgregarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBancoActionPerformed
        // TODO add your handling code here:
        limpiarTableBanco();
        Banco tipo = new Banco();
        tipo.setId_banco(Integer.parseInt(txtIdBanco.getText()));
        tipo.setNombreBanco(txtNombreBanco.getText());
        tipo.setTelefonoBanco(Integer.parseInt(txtTelefonoBanco.getText()));
        tipo.setDireccionBanco(txtDireccionBanco.getText());
        tipo.setPaginaBanco(txtPaginaBanco.getText());
        tipo.setGmailBanco(txtGmailBanco.getText());
        ControladorBanco controlador = new ControladorBanco();
        controlador.agregarBanco(tipo);
        //limpiarTableBanco();
        listarBanco();

        txtIdBanco.setText("");
        txtNombreBanco.setText("");
        txtTelefonoBanco.setText("");
        txtDireccionBanco.setText("");
        txtPaginaBanco.setText("");
        txtGmailBanco.setText("");
    }//GEN-LAST:event_btnAgregarBancoActionPerformed

    private void btnEliminarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBancoActionPerformed
        // TODO add your handling code here:
        limpiarTableBanco();
        Banco tipo = new Banco();
        if (!"".equals(txtIdEliminarBanco.getText())) {
            tipo.setId_banco(Integer.parseInt(txtIdEliminarBanco.getText()));
            ControladorBanco controlador = new ControladorBanco();
            controlador.eliminarBanco(tipo);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para eliminarlo");
        }
        listarBanco();
        txtIdBanco.setText("");
        txtNombreBanco.setText("");
        txtTelefonoBanco.setText("");
        txtDireccionBanco.setText("");
        txtPaginaBanco.setText("");
        txtGmailBanco.setText("");

    }//GEN-LAST:event_btnEliminarBancoActionPerformed

    private void btnActualizarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBancoActionPerformed
        // TODO add your handling code here:
        limpiarTableBanco();
        Banco tipo = new Banco();
        if (!"".equals(txtIdBanco.getText())) {
            tipo.setId_banco(Integer.parseInt(txtIdBanco.getText()));
            tipo.setNombreBanco(txtNombreBanco.getText());
            tipo.setTelefonoBanco(Integer.parseInt(txtTelefonoBanco.getText()));
            tipo.setDireccionBanco(txtDireccionBanco.getText());
            tipo.setPaginaBanco(txtPaginaBanco.getText());
            tipo.setGmailBanco(txtGmailBanco.getText());
            ControladorBanco controlador = new ControladorBanco();
            controlador.actualizarProveedor(tipo);

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el id del objeto para actualizarlo");
        }
        listarBanco();

        txtIdBanco.setText("");
        txtNombreBanco.setText("");
        txtTelefonoBanco.setText("");
        txtDireccionBanco.setText("");
        txtPaginaBanco.setText("");
        txtGmailBanco.setText("");

    }//GEN-LAST:event_btnActualizarBancoActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        limpiarTableProveedores();
        jTabbedPane1.setSelectedIndex(2);
        listarProveedores();

    }//GEN-LAST:event_btnProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBanco;
    private javax.swing.JButton btnActualizarProveedor;
    private javax.swing.JButton btnActualizarServicio;
    private javax.swing.JButton btnActualizarTipoCuenta;
    private javax.swing.JButton btnActualizarTipoMoneda;
    private javax.swing.JButton btnAgregarBanco;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnAgregarTipoCuenta;
    private javax.swing.JButton btnAgregarTipoMoneda;
    private javax.swing.JButton btnDatosBanco;
    private javax.swing.JButton btnEliminarBanco;
    private javax.swing.JButton btnEliminarMoneda;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnEliminarTipoCuenta;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTipoCuentas;
    private javax.swing.JButton btnTipoMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableBanco;
    private javax.swing.JTable tableProveedores;
    private javax.swing.JTable tableServicios;
    private javax.swing.JTable tableTipoCuentas;
    private javax.swing.JTable tableTipoMoneda;
    private javax.swing.JTextField txtDireccionBanco;
    private javax.swing.JTextField txtGmailBanco;
    private javax.swing.JTextField txtIdBanco;
    private javax.swing.JTextField txtIdEliminarBanco;
    private javax.swing.JTextField txtIdEliminarProveedor;
    private javax.swing.JTextField txtIdEliminarServicio;
    private javax.swing.JTextField txtIdEliminarTipoCuenta;
    private javax.swing.JTextField txtIdMonedaEliminar;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtIdTipoCuenta;
    private javax.swing.JTextField txtIdTipoMoneda;
    private javax.swing.JTextField txtNombreBanco;
    private javax.swing.JTextField txtPaginaBanco;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTelefonoBanco;
    private javax.swing.JTextField txtTipoCuenta;
    private javax.swing.JTextField txtTipoMoneda;
    // End of variables declaration//GEN-END:variables
}
